In [ ]:
import numpy as np

## Data Types & Attributes

In [ ]:
# Numpy's main data structure is the multidimensional array called ndarray

a1 = np.array([1, 2, 3, 4, 5])
a1

In [ ]:
type(a1)

In [ ]:
a2 = np.array([[1, 2, 3], 
               [4, 5, 6], 
               [7, 8, 9]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [ ]:
a2

In [ ]:
a3

In [ ]:
a1.shape

In [ ]:
a2.shape

In [ ]:
a3.shape

In [ ]:
a1.ndim, a2.ndim, a3.ndim

In [ ]:
a1.dtype, a2.dtype, a3.dtype

In [ ]:
a1.size, a2.size, a3.size

In [ ]:
type(a1), type(a2), type(a3)

In [ ]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

## Creating arrays

In [ ]:
sample_array = np.array([1,2,3])
sample_array

In [ ]:
sample_array.dtype

In [ ]:
ones = np.ones((2, 3))

In [ ]:
ones

In [ ]:
ones.dtype 

In [ ]:
type(ones)

In [ ]:
zeros = np.zeros((2, 3))

In [ ]:
range_array = np.arange(0, 10, 2)

In [ ]:
range_array

In [ ]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

In [ ]:
random_array.size

In [ ]:
random_array.shape

In [ ]:
random_array_2 = np.random.random((5, 3))
random_array_2

In [ ]:
random_array_2.shape

In [ ]:
# Pseudo-random numbers
# seed is a parameter that allows us to generate the same random numbers
np.random.seed(seed = 0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

In [ ]:
random_array_4.shape

## Viewing arrays and matrices

In [ ]:
# unique() returns the unique values in an array
np.unique(random_array_4)

In [ ]:
np.unique(a1)

In [ ]:
a1[0]

In [ ]:
a2[0]

In [ ]:
a3[0]

In [ ]:
a3[:2, :2, :2]

In [ ]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))

In [ ]:
a4

In [ ]:
a4.shape, a4.ndim

In [ ]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :4]

# Manipulating and comparing arrays

### Arithmetic Operations

In [ ]:
a1

In [ ]:
ones = np.ones(len(a1))

In [ ]:
ones

In [ ]:
a1 + ones

In [ ]:
a2

* broadcasting is the ability to perform operations on arrays of different shapes.

* Smaller array is broadcasted to the larger array

In [ ]:
np.log(a1)

In [ ]:
np.exp(a1)

In [ ]:
np.sqrt(a1)

### Aggregation: the formation of a number of things into a cluster. Perform same method on same type of object

In [ ]:
list_1 = [1, 2, 3]
type(list_1)

In [ ]:
sum(list_1)

In [ ]:
a1

In [ ]:
type(a1)

In [ ]:
sum(a1)

In [ ]:
np.sum(a1)

In [ ]:
# Creative a massive Numpy array

massive_array = np.random.random(10000)
massive_array[:100]

In [ ]:
# timeit function is a magic function in python, which will show how much time it had taken to perform particualr operation we are passing
%timeit sum(massive_array)

In [ ]:
# treating the array as numpy data type
%timeit np.sum(massive_array)

* Just see the time diffrence above

In [ ]:
np.mean(massive_array)

In [ ]:
np.sum(massive_array)

In [ ]:
np.max(massive_array)

In [ ]:
np.min(massive_array)

In [ ]:
# Standard Deviation is a measure which shows how much variation (such as spread, dispersion, spread,) from the mean exists.
np.std(massive_array)

In [ ]:
# Variance is the measure of how notably a collection of data is spread out. If all the data values are identical, then it indicates the variance is zero.
np.var(massive_array)

 # Standard deviation = squareroot of varience

In [ ]:
# Demo of std and var
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

In [ ]:
np.var(high_var_array), np.var(low_var_array)

In [ ]:
np.std(high_var_array), np.std(low_var_array)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

plt.hist(high_var_array)
plt.show()

In [ ]:
plt.hist(low_var_array)
plt.show()

## Reshaping and Transposing

In [ ]:
a2 = np.array([[1, 2, 3],[4,5,6]])

In [ ]:
a2.shape

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a2_reshape = a2.reshape(2, 3, 1)
a2_reshape

In [ ]:
a2_reshape * a3

In [ ]:
# Transpose swap row and column
a2.T

In [ ]:
a2

In [ ]:
a2.T.shape, a2.shape

In [ ]:
a3.shape, a3.T.shape

## Dot product

In [ ]:
np.random.seed(0)

mat1 = np.random.randint(10, size = (5,3))

In [ ]:
mat2 = np.random.randint(10, size = (5,3))

In [ ]:
mat1

In [ ]:
mat2

In [ ]:
mat1.shape, mat2.shape

In [ ]:
mat2 = mat2.T

In [ ]:
mat2.shape

In [ ]:
np.dot(mat1, mat2)

In [ ]:
mat1 > mat2.T

In [ ]:
mat1 > 5

In [ ]:
mat1 >= mat2.T

In [ ]:
mat1 == mat2.T

## Sorting Array

In [ ]:
random_array

In [ ]:
random_array.shape

In [ ]:
np.sort(random_array)

In [ ]:
np.argsort(random_array)

In [ ]:
a1

In [ ]:
np.argsort(a1)

In [ ]:
np.argmin(a1)

In [ ]:
np.argmin(random_array), np.argmin(random_array_2)

# Numpy turning image in array

In [14]:
from matplotlib import *

In [15]:
panda = imread("images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [16]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [17]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

The above function turn picture in array by:
the picture of made of many pixel. Each pixel have it's own color or maybe group. So what imread done it recorded the color code of each pixel of the photo 

In [18]:
car = imread("images/car-photo.png")

In [19]:
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

In [20]:
dog = imread("images/dog-photo.png")

In [21]:
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274

In [22]:
dog[:1]

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]]], dtype=float32)