In [1]:
import numpy as np

## Data Types & Attributes

In [2]:
# Numpy's main data structure is the multidimensional array called ndarray

a1 = np.array([1, 2, 3, 4, 5])
a1

array([1, 2, 3, 4, 5])

In [3]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1, 2, 3], 
               [4, 5, 6], 
               [7, 8, 9]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [8]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a1.shape

(5,)

In [11]:
a2.shape

(3, 3)

In [12]:
a3.shape

(2, 3, 3)

In [14]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [15]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))